apiVersion: v1
kind: ConfigMap
metadata:
  name: database
  namespace: gitea
  labels:
    app: gitea
data:
  DB_TYPE: postgres
  DB_HOST: 5435
  DB_NAME: gitea
  DB_USER: root
  DB_PASSWD: some_super_secret_random_amazing_password123
---

