apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres
  namespace: gitea
  labels:
    app: gitea
data:
  DB_PASSWD: "c29tZV9zdXBlcl9zZWNyZXRfcmFuZG9tX2FtYXppbmdfcGFzc3dvcmQxMjMK"
---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: registry
  namespace: gitea
  labels:
    app: gitea
data:
  REGISTRY_HTTP_SECRET: UjJzeXRmQzZJQ1REZ2dGb3BoZUZRc20xekp0TnFtcmd1UUp4dUxUbgo=