apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data
  namespace: gitea
  labels:
    volume-name: gitea-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: 50Gi
  hostPath:
    path: /mnt/kubernetes/gitea-data
