apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitea
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
  GITEA_ADMIN_PASSWORD: {{ .Values.admin.password | b64enc }}
---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
  DB_PASS: {{ .Values.database.password | b64enc }}
