apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.data.name }}
  namespace: {{ .Values.namespace }}
  labels:
    volume-name: {{ .Values.volumes.data.name }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: {{ .Values.volumes.data.size }}
  hostPath:
    path: {{.Values.volumes.mountLocation }}/{{ .Values.volumes.data.name }}
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.postgres.name }}
  namespace: {{ .Values.namespace }}
  labels:
    volume-name: {{ .Values.volumes.postgres.name }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: {{ .Values.volumes.postgres.size }}
  hostPath:
    path: {{.Values.volumes.mountLocation }}/{{ .Values.volumes.postgres.name }}
---

